#
# Docker Compose file for Openstad app
#
---
version: '3.1'
services:
  frontend:
    command: npm run dev
    image: ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
    ports:
      - ${FRONTED_PORT}:${FRONTED_PORT}
    environment:
      PORT: "${FRONTED_PORT}"
      DB_HOST: "${FRONTEND_MONGO_DB_HOST}"
      DB_PORT: "${FRONTEND_MONGO_PORT}"
      MONGO_DB_HOST: "${FRONTEND_MONGO_DB_HOST}"
      MINIFY_JS: "${FRONTEND_MINIFY_JS}"
      COOKIE_SECURE_OFF: "${COOKIE_SECURE_OFF}"
      DOCKER_PUBLIC_USERNAME: "openstad"
      DOCKER_IMAGE_NAME: "frontend"
      K8S_DEPLOYMENT_NAME: "openstad-frontend"
      K8S_NAMESPACE: "openstad"
      FRONTED_PORT: "4444"
      FRONTEND_MONGO_SCHEME: "mongodb://mongo"
      FRONTEND_MONGO_DB_HOST: "mongo"
      FRONTEND_MONGO_PORT: "27017"
      FRONTEND_MINIFY_JS: "ON"
      COOKIE_SECURE_OFF: "yes"
      API: "http://localhost:8111"
      IMAGE_API_URL: "http://localhost:3333"
      IMAGE_API_ACCESS_TOKEN: "xxxx"
      IMAGE_API_ACCESS_TOKEN: "xxxx"
      SITE_API_KEY: "xxxx"
      DEFAULT_DB: "localhost2"
      DEFAULT_HOST: "localhost:4444"
      APP_URL: "http://localhost:4444"
      restart: always"

    links:
      - mongo:localhost
    depends_on:
      - mongo

  mongo:
    image: 'mongo:4.0'
    ports:
      - '127.0.0.1:27018:27017'
    restart: always
