# automatically publishes v tags to dockerhub.
# so for instance v0.5.1 wil publish but randtom wont
name: Build and Publish Version Tags
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build Docker image and push to repositories
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
        mongodb-version: [4.2, 4.4, 5.0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Set CURRENT_BRANCH
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - run: mongo default --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

      - run: echo '${{ env.CURRENT_BRANCH}}' > branch.txt

      - run: npm install --production

      - run: npm run test -- --coverage

      - run: mkdir assets

      - run: NODE_ENV=production APOS_MINIFY=1 APOS_WORKFLOW=ON APOS_BUNDLE=assets node apostrophe.js apostrophe:generation

      #   - name: tag number
      #        run : echo ${{ github.event.release.tag_name }}

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # Note: tags has to be all lower-case
          tags: |
            openstad/frontend:${{ steps.get_version.outputs.VERSION }}
          # build on feature branches, push only on main branch
          ##push: ${{ github.ref == 'refs/heads/main' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

       